### PR TITLE
chore: Remove GetEncodingConfig method

### PR DESCRIPTION
**Pull request by vitsalis**
Entities using the `GetEncodingConfig()` method of the rpc-client receive an encoder/decoder that contains the `ModuleBasics` for Babylon modules and all `ModuleBasics` implemented by the lens client. However, the lens client does uses the upstream IBC repository instead of our fork, meaning that due to inconsistencies, the encoders/decoders won't work with messages created using our fork of ibc-go.

Another option is for applications to directly import `github.com/babylonchain/babylon/app` and use the `GetEncodingConfig` method that it implements. However, the `app` package of the Babylon repo has dependencies in CosmWasm, which will introduce this transitive dependencies to other repos. This transitive dependency requires building on linux images more difficult in the sense that they need to install wasm binaries etc (see this [PR](https://github.com/babylonchain/babylon/pull/324/files#diff-f83a1cf632e5e661ae0e21d5bbe4c3681b6dfd55320afb16756649a7843674d7)).

Therefore, I think the best course of action (while we still have a fork) would be to add the module basics to the encoder maintained by the rpc-client. If we don't want to do this and instead rely on the `app` package, then the functionality for getting the encoding config from the rpc client can be removed entirely.

### CODE REVIEW

**Comment by vitsalis** [comment]
There are still some decoding issues on the API side which are resolved if we use the Babylon encoding config. Converting to draft for now.

**Comment by vitsalis** [comment]
Just noticed that lens client doesn't have wasm ModuleBasics included, so we would have to import them eitherway, if we want applications such as the API to query contract related stuff (which will probs happen in the future). Therefore, I'll be removing this `GetEncodingConfig` and instead applications would have to use the one defined on the Babylon repository for consistency.

**Comment by SebastianElvis** [comment]
> However, the lens client does uses the upstream IBC repository instead of our fork, meaning that due to inconsistencies, the encoders/decoders won't work with messages created using our fork of ibc-go.

A quick question: given that our IBC-Go fork does not (and will not) touch the encoding/decoding stuff, maybe it's fine?

**Comment by vitsalis** [comment]
> A quick question: given that our IBC-Go fork does not (and will not) touch the encoding/decoding stuff, maybe it's fine?

The API had issues decoding IBC related messages using the encoder provided by the `rpc-client`. When I added our own ibc-go module basics to the `rpc-client` it could decode them, but it had issues decoding some proto messages. I figure it is due to an inconsistency between our fork and the ibc-go that lens maintains.

**Review by SebastianElvis — APPROVED** [review]
Lgtm! Thanks for addressing this.

**Comment by vitsalis** [comment]
> > A quick question: given that our IBC-Go fork does not (and will not) touch the encoding/decoding stuff, maybe it's fine?
> 
> The API had issues decoding IBC related messages using the encoder provided by the `rpc-client`. More specifically, I had errors of this kind:
> 
> ```
> unable to resolve type URL /ibc.lightclients.tendermint.v1.Header: tx parse error
> ```
> 
> When I added our own ibc-go module basics to the `rpc-client` (see [commit](https://github.com/babylonchain/rpc-client/pull/35/commits/e77d2fe689727cd98e67fec35a8047c560308721)) it could decode them, but it had issues decoding some proto messages with `illegal wiretype` types of errors. I figure the IBC related errors are due to an inconsistency between our fork and the ibc-go that lens maintains while the rest I'm not entirely sure. They were all gone when I added the Babylon encoding config and the wasm dependency.

What is weird for me though is that after I updated the rpc-client module basics to include our own fork of IBC related stuff (see [commit](https://github.com/babylonchain/rpc-client/pull/35/commits/e77d2fe689727cd98e67fec35a8047c560308721)), I was getting `illegal wiretype` proto errors, but not on places that depended in which the `GetEncodingConfig` method that is removed here was referenced, but on entirely different endpoints. Once I added the wasm dependency, those errors were gone. Any thoughts why could this happen?

**Comment by SebastianElvis** [comment]
No particular clue 😅 perhaps the Wasm dependency contains something related to encoding/decoding of `x/wasm` module?

**Comment by vitsalis** [comment]
> No particular clue 😅 perhaps the Wasm dependency contains something related to encoding/decoding of `x/wasm` module?

Not getting this error anymore so I guess it's related to the API side.

**Pull request merged**
